[package]
name = "ps-render-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4.13"
ps-render = { path = "../crates/ps-render" }

[[bin]]
name = "render"
path = "fuzz_targets/render.rs"
test = false
doc = false
bench = false
