[package]
name = "ps-render"
version = "0.1.0"
edition.workspace = true
publish.workspace = true
rust-version.workspace = true

[lib]
path = "src/lib.rs"

[dependencies]
ammonia = "4.1.4"
blake3 = "1.8.6"
ps-core = { version = "0.1.0", path = "../ps-core" }
pulldown-cmark = { version = "0.13.4", default-features = false, features = ["html"] }
thiserror = "2.0.20"

[dev-dependencies]
tempfile = "3.27.0"
