//! TypeScript declarations for values that cross the Tauri IPC boundary.

use ts_rs::{Config as TsConfig, TS};

use crate::config::{
    Appearance, Config, Editor, Files, History, Typography, Updates, ViewMode, Viewer, Window,
};
use crate::docio::{
    DocChunkEvent, DocDoneEvent, DocOpenResult, DocumentEncoding, DocumentMeta, DocumentSource,
    LineEnding, RestoreTraits, TocEntry, WrittenDocument,
};
use crate::fsops::{ConflictStrategy, UntitledKind};
use crate::projects::{OpenDropResult, Project, ProjectsListQuery, ProjectsListResult};
use crate::themes::{ThemeAppearance, ThemeInfo};
use crate::tree::{TreeNode, TreeNodeKind};
use crate::watch::{FsChangedEvent, WatchUpdate};

const HEADER: &str = "/* eslint-disable */\n// Generated by ps-core. Do not edit.\n\n";

fn ts_config() -> TsConfig {
    TsConfig::new().with_large_int("number")
}

/// Assembles a single TypeScript module for every IPC type.
pub fn ipc_typescript() -> String {
    let ts = ts_config();
    let declarations = [
        ViewMode::decl(&ts),
        Appearance::decl(&ts),
        Typography::decl(&ts),
        Viewer::decl(&ts),
        Editor::decl(&ts),
        History::decl(&ts),
        Files::decl(&ts),
        Window::decl(&ts),
        Updates::decl(&ts),
        Config::decl(&ts),
        Project::decl(&ts),
        ProjectsListQuery::decl(&ts),
        ProjectsListResult::decl(&ts),
        OpenDropResult::decl(&ts),
        TreeNodeKind::decl(&ts),
        TreeNode::decl(&ts),
        ConflictStrategy::decl(&ts),
        UntitledKind::decl(&ts),
        LineEnding::decl(&ts),
        RestoreTraits::decl(&ts),
        DocumentEncoding::decl(&ts),
        TocEntry::decl(&ts),
        DocumentSource::decl(&ts),
        WrittenDocument::decl(&ts),
        DocumentMeta::decl(&ts),
        DocOpenResult::decl(&ts),
        DocChunkEvent::decl(&ts),
        DocDoneEvent::decl(&ts),
        WatchUpdate::decl(&ts),
        FsChangedEvent::decl(&ts),
        ThemeAppearance::decl(&ts),
        ThemeInfo::decl(&ts),
    ];

    let mut module = String::from(HEADER);
    for (index, declaration) in declarations.iter().enumerate() {
        if index > 0 {
            module.push('\n');
        }
        module.push_str("export ");
        module.push_str(declaration.trim());
        module.push('\n');
    }
    module
}

/// Workspace-relative path of the committed TypeScript bindings.
pub fn bindings_path() -> std::path::PathBuf {
    std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../ui/src/lib/generated/core.ts")
}
